name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug - List Environment Variables
        run: echo "$AWS_ACCESS_KEY_ID"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1  # Substitua pela sua região desejada

      - name: Install Dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Zip Lambda Function
        run: zip -r aimbere-mail-lambda.zip dist/*

      - name: Debug - List Files
        run: ls -R

      - name: Debug - AWS CLI Configuration
        run: aws configure list

      - name: Upload to S3
        run: aws s3 cp aimbere-mail-lambda.zip s3://aimbere-mail-lambda-bucket

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name aimbere-mail-lambda \
            --s3-bucket aimbere-mail-lambda-bucket \
            --s3-key aimbere-mail-lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
